# docs/mkdocs.yml

## Deshabilita la detección errónea de URL por parte de TechDocs
repo_url:  https://github.com/EleazarBT/demo
edit_uri:  tree/main/docs/

site_name: Demo Spring Boot Service
nav:
  - Visión general: index.md
  - API Markdown: api.md
  - JavaDoc HTML: javadoc/index.html

plugins:
  - search
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.superfences
